# -*- coding: utf-8 -*-
"""scrap using selenium.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gWCkiVtOtwKyi3_gMgq3vMc3_7jkwbQ
"""

# pip install selenium

# pip install chromedriver_autoinstaller

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time
import csv
import numpy as np
import pandas as pd

# import os
# import sys
# os.path.dirname(sys.executable)

service = Service(executable_path='C:/Users/linkc/miniconda3/envs/conda1/chromedriver.exe')
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(service=service, options=options)

url = 'https://www.visionplus.id/movies'
driver.get(url)

import csv

base = driver.find_elements(By.CLASS_NAME, "swiper-box")
data = []

for item in base:
    tipe = item.find_element(By.CLASS_NAME, "title-container").find_element(By.TAG_NAME, "h2").text

    p = item.find_element(By.CLASS_NAME, "swiper-container").find_element(By.CLASS_NAME, "swiper-wrapper")
    items_in_p = p.find_elements(By.CLASS_NAME, "swiper-slide")

    group_data = []
    group_data.append(tipe)

    for item1 in items_in_p:
        title = item1.find_element(By.CLASS_NAME, "img-wrapper-ratio").find_element(By.TAG_NAME, "img").get_attribute("alt")

        title = title.split("poster", 1)[-1].strip()

        group_data.append(title)

    data.append(group_data)

with open('movie_data.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Movie Type', 'Movie'])

    for group_data in data:
        writer.writerow([group_data[0], group_data[1]])
        for i in range(2, len(group_data)):
            writer.writerow(['', group_data[i]])